api_platform:
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header

    formats:
    jsonld: ['application/ld+json']
    json: ['application/json']